[project]
name = "mml-gaussian-micture-fitting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.11.28",
    "pandas>=2.2.3",
]

[dependency-groups]
dev = [
    "ruff>=0.11.2",
]
